### ISSUE TITLE
ツイートに分離可能な小説

### ISSUE THREAD

**Issue by sounisi5011** [sounisi5011/sounisi5011.jp#52]
段落毎にURLフラグメントを割り当て、対応するTwitter Cardを割り当て、段落の文字数を制限すれば、Twitterでツイートしつつ作品を宣伝する事が可能になる。[ページを移動すること無く作品の内容全てを読める](https://twitter.com/sounisi5011Vore/status/1147020996097896449)大きな利点。

* ツイートの文字数計測：[twitter-text](https://www.npmjs.com/package/twitter-text)
* Twitter CardでURLフラグメント：フラグメント付きURLにリダイレクトする専用ページの自動生成

**Comment by sounisi5011** [comment]
URLフラグメントは正しく機能するだろうか？
このサイトでは、ヘッダーを固定表示している。このズレが、URLフラグメントを正しくない位置に移動させてしまう要因になるのではないだろうか？

**Comment by sounisi5011** [comment]
> URLフラグメントは正しく機能するだろうか？
> このサイトでは、ヘッダーを固定表示している。このズレが、URLフラグメントを正しくない位置に移動させてしまう要因になるのではないだろうか？

QRコードの画像サイズはデカい。だから、このサイズを利用して、ヘッダの開始位置をずらすスタイルを自動生成するのはどうだろう？
折り返したURLの高さがQRコードを超えるような場合は、短いJSのコードで対処すればいい。

**Comment by sounisi5011** [comment]
> > URLフラグメントは正しく機能するだろうか？
> > このサイトでは、ヘッダーを固定表示している。このズレが、URLフラグメントを正しくない位置に移動させてしまう要因になるのではないだろうか？
> 
> QRコードの画像サイズはデカい。だから、このサイズを利用して、ヘッダの開始位置をずらすスタイルを自動生成するのはどうだろう？
> 折り返したURLの高さがQRコードを超えるような場合は、短いJSのコードで対処すればいい。

URLが折り返す位置は確定している。ここから、URLが全て折り返した場合の最大幅を判定できるように思う。

**Comment by sounisi5011** [comment]
> URLフラグメントは正しく機能するだろうか？
> このサイトでは、ヘッダーを固定表示している。このズレが、URLフラグメントを正しくない位置に移動させてしまう要因になるのではないだろうか？

`scroll-margin`プロパティを使用して、`id`属性付き`p`要素をズレるように指定するのが良いかもしれない。
参考：https://stackoverflow.com/a/55683966/4907315

**Comment by sounisi5011** [comment]
> > URLフラグメントは正しく機能するだろうか？
> > このサイトでは、ヘッダーを固定表示している。このズレが、URLフラグメントを正しくない位置に移動させてしまう要因になるのではないだろうか？
> 
> `scroll-margin`プロパティを使用して、`id`属性付き`p`要素をズレるように指定するのが良いかもしれない。

軽く検証してみたところ、`body`要素に`scroll-padding-top`プロパティを指定すると、スクロールが上手く調節されるようだ。
一方、`scroll-margin-top`プロパティは、URLフラグメントでスクロールを試みる`id`属性を持った各要素に指定しなくてはならないらしい。

**Comment by sounisi5011** [comment]
> > > URLフラグメントは正しく機能するだろうか？
> > > このサイトでは、ヘッダーを固定表示している。このズレが、URLフラグメントを正しくない位置に移動させてしまう要因になるのではないだろうか？
> > 
> > 
> > `scroll-margin`プロパティを使用して、`id`属性付き`p`要素をズレるように指定するのが良いかもしれない。
> 
> 軽く検証してみたところ、`body`要素に`scroll-padding-top`プロパティを指定すると、スクロールが上手く調節されるようだ。
> 一方、`scroll-margin-top`プロパティは、URLフラグメントでスクロールを試みる`id`属性を持った各要素に指定しなくてはならないらしい。

`scroll-*-top`プロパティは使用しないほうが良いかもしれない。以下の記事によると、このようなLonghands構文をChromeがサポートしていない時期があったようだ。

参考：https://css-tricks.com/almanac/properties/s/scroll-margin/#syntax

よって、このような記述が有効だと思われる。

```css
scroll-padding: <header-height> 0 <footer-height>;
```

**Comment by sounisi5011** [comment]
> > > URLフラグメントは正しく機能するだろうか？
> > > このサイトでは、ヘッダーを固定表示している。このズレが、URLフラグメントを正しくない位置に移動させてしまう要因になるのではないだろうか？
> > 
> > 
> > `scroll-margin`プロパティを使用して、`id`属性付き`p`要素をズレるように指定するのが良いかもしれない。
> 
> 軽く検証してみたところ、`body`要素に`scroll-padding-top`プロパティを指定すると、スクロールが上手く調節されるようだ。
> 一方、`scroll-margin-top`プロパティは、URLフラグメントでスクロールを試みる`id`属性を持った各要素に指定しなくてはならないらしい。

以下のページにいろいろな情報が。`html`要素で`scroll-padding`プロパティが効かないのはChromeのバグらしい。
それ以外にも、`scroll-padding`プロパティに対応していないブラウザ向けの記述もある。要確認。

[ページ内リンクが固定ヘッダと重なって隠れる問題を解決するCSSのテクニック | コリス](https://coliss.com/articles/build-websites/operation/css/fixed-headers-on-page-links-and-overlapping-content.html)

**Comment by sounisi5011** [comment]
`CSS.supports()`メソッドを使用して`position: sticky`または`position: -webkit-sticky`に対応しているか判定してから、`scroll-padding`プロパティまたはその[フォールバック](https://css-tricks.com/hash-tag-links-padding/#article-header-id-1)のスタイルをJavaScriptで変更する方法が有効だろう。

`CSS.supports()`メソッドに対応していない環境は考慮しなくてもいい。
なぜなら、Safari 6-8（と、"experimental Web Platform features"フラグを有効にしたChrome 23-27）を除いて、[`position: sticky`プロパティに対応しているブラウザ](https://caniuse.com/#feat=css-sticky)は[`CSS.supports()`メソッドにも対応](https://caniuse.com/#feat=css-supports-api)しているから。
例外のSafari（とChrome）も、[`@supports`ルールに対応しているブラウザ](https://caniuse.com/#feat=css-featurequeries)からは除外される。
よって、`position: sticky`プロパティを`@supports`ルールで判定している限り、`CSS.supports()`メソッドに対応していない環境＝`position: sticky`プロパティに確実に対応していない環境、とみなして良いだろう。同じ理由から、Presto時代のOperaが使える関数`supportsCSS()`も判定から除外していい。

※逆はあり得る。すなわち、`CSS.supports()`メソッドに対応していて、`position: sticky`プロパティに対応していない環境は、ほとんどのブラウザが該当する。`position: sticky`プロパティの対応状況は判定する必要がある。

**Comment by sounisi5011** [comment]
> `CSS.supports()`メソッドを使用して`position: sticky`または`position: -webkit-sticky`に対応しているか判定してから、`scroll-padding`プロパティまたはその[フォールバック](https://css-tricks.com/hash-tag-links-padding/#article-header-id-1)のスタイルをJavaScriptで変更する方法が有効だろう。
> 
> `CSS.supports()`メソッドに対応していない環境は考慮しなくてもいい。
> なぜなら、Safari 6-8（と、"experimental Web Platform features"フラグを有効にしたChrome 23-27）を除いて、[`position: sticky`プロパティに対応しているブラウザ](https://caniuse.com/#feat=css-sticky)は[`CSS.supports()`メソッドにも対応](https://caniuse.com/#feat=css-supports-api)しているから。
> 例外のSafari（とChrome）も、[`@supports`ルールに対応しているブラウザ](https://caniuse.com/#feat=css-featurequeries)からは除外される。
> よって、`position: sticky`プロパティを`@supports`ルールで判定している限り、`CSS.supports()`メソッドに対応していない環境＝`position: sticky`プロパティに確実に対応していない環境、とみなして良いだろう。同じ理由から、Presto時代のOperaが使える関数`supportsCSS()`も判定から除外していい。
> 
> ※逆はあり得る。すなわち、`CSS.supports()`メソッドに対応していて、`position: sticky`プロパティに対応していない環境は、ほとんどのブラウザが該当する。`position: sticky`プロパティの対応状況は判定する必要がある。

つまり、静的に生成するべき`style`要素（あとからJavaScriptで上書きするもの）はこれになるわけだ？

```html
<style id=scroll-padding-style>
@supports ((position: -webkit-sticky) or (position:sticky)) {
  @supports (scroll-margin-top: 42px) {
    /*
     * Chrome v73+ only works with <body>.
     * ULTIMATELY this needs to go on <html>, not <body>.
     * see https://css-tricks.com/fixed-headers-on-page-links-and-overlapping-content-oh-my/
     */
    html, body {
      scroll-margin-top: 42px;
    }
  }

  @supports not (scroll-margin-top: 42px) {
    /* see https://css-tricks.com/hash-tag-links-padding/#article-header-id-1 */
    /* see http://nicolasgallagher.com/jump-links-and-viewport-positioning/demo/#method-B */
    p[id]:before {
      display: block;
      content: " ";
      margin-top: -42px;
      height: 42px;
      visibility: hidden;
      pointer-events: none;
    }
  }
}
</style>
```

**Comment by sounisi5011** [comment]
> つまり、静的に生成するべき`style`要素（あとからJavaScriptで上書きするもの）はこれになるわけだ？
> 
> ```
> <style id=scroll-padding-style>
> @supports ((position: -webkit-sticky) or (position:sticky)) {
>   @supports (scroll-margin-top: 42px) {
>     /*
>      * Chrome v73+ only works with <body>.
>      * ULTIMATELY this needs to go on <html>, not <body>.
>      * see https://css-tricks.com/fixed-headers-on-page-links-and-overlapping-content-oh-my/
>      */
>     html, body {
>       scroll-margin-top: 42px;
>     }
>   }
> 
>   @supports not (scroll-margin-top: 42px) {
>     /* see https://css-tricks.com/hash-tag-links-padding/#article-header-id-1 */
>     /* see http://nicolasgallagher.com/jump-links-and-viewport-positioning/demo/#method-B */
>     p[id]:before {
>       display: block;
>       content: " ";
>       margin-top: -42px;
>       height: 42px;
>       visibility: hidden;
>       pointer-events: none;
>     }
>   }
> }
> </style>
> ```

CSSのカスタムプロパティを使用して単純化できない？

```css
@supports ((position: -webkit-sticky) or (position:sticky)) {
  @supports (scroll-margin-top: var(--header-height)) {
    /*
     * Chrome v73+ only works with <body>.
     * ULTIMATELY this needs to go on <html>, not <body>.
     * see https://css-tricks.com/fixed-headers-on-page-links-and-overlapping-content-oh-my/
     */
    html, body {
      scroll-margin-top: var(--header-height);
    }
  }

  @supports not (scroll-margin-top: var(--header-height)) {
    /* see https://css-tricks.com/hash-tag-links-padding/#article-header-id-1 */
    /* see http://nicolasgallagher.com/jump-links-and-viewport-positioning/demo/#method-B */
    p[id]:before {
      display: block;
      content: " ";
      margin-top: calc(var(--header-height) * -1);
      height: var(--header-height);
      visibility: hidden;
      pointer-events: none;
    }
  }
}
```

```html
<html style="--header-height: 42px">
...
</html>
```
